### ISSUE TITLE
특정 노트를 수정하는 동안 메인 윈도우에 수정 내용이 반영되지 않습니다.

### ISSUE THREAD

**Issue by ShapeLayer** [Ha-limLee/Sticky-Notes-Improved#22]
단일 창을 사용하는 앱이 아니라 여러개의 윈도우를 생성하는 앱이기 때문에, 노트 윈도우를 닫을 때만 내용을 처음부터 다시 불러오는건 특정 노트를 수정하는 동안 메인 윈도우에 수정 내용이 반영되지 않습니다.

~~또 페이지 전체를 다시 불러오면 메인 페이지 전체가 깜빡이게 되는데,~~ 혹시 mainWindow의 프론트 단(컴포넌트 내부에서 정의)에서 setInterval을 사용하여 수정 사항을 일부만 주기적으로 불러오는 방법은 어떨까요? 계속해서 관련 기능을 호출해야하지만, 호출에 소모되는 리소스는 많이 적을 것 같습니다.

```
* 리액트는 문서 내용을 수정할 때 문서 전체나 컴포넌트 전체를 수정하는 것이 아니라 수정된 내용 일부만 수정하는 방식을 채택하고 있습니다.
```

_Originally posted by @ShapeLayer in https://github.com/Ha-limLee/Sticky-Notes-Improved/pull/19#discussion_r638079701_

**Comment by Ha-limLee** [comment]
메인 윈도우는 미리보기 역할을 합니다.
사용자는 노트를 수정할 때 전체 내용을 다 보고 있습니다.
그러니 그 내용을 굳이 메인 윈도우에 보여줄 필요는 없다고 생각합니다.

혹시 그런 기능이 필요한 이유가 있을까요?

**Comment by ShapeLayer** [comment]
메인 윈도우와 노트 윈도우는 개별 윈도우입니다.  
원래대로라면 그 둘은 겹쳐지지 않은 상태여야 하고(겹쳐진 상태로 창이 생성된다면 사용자는 창이 여러개 임을 인지하기 힘들 수 있습니다.), 사용자는 두가지 윈도우를 모두 보게 됩니다. 내부적으로 메모를 저장하고 있다고 해도 메인 윈도우에 반영되지 않는다면, 사용자 입장에서 메모가 저장되지 않고 있다고 판단하기 쉬울 것이라 생각합니다. 더군다나 메인 윈도우에 포커스가 맞춰져 있을 때도 메모가 변경 사항을 반영하지 못하고 있다면, 자연스럽게 사용자는 저장 버튼을 찾으려고 할 지도 모릅니다.
