### ISSUE TITLE
Separate the note window from the lobby window (main window)

### ISSUE THREAD

**Issue by ShapeLayer** [Ha-limLee/Sticky-Notes-Improved#7]
Start work when [feature/pr-pending-1](https://github.com/Ha-limLee/Sticky-Note-Improved/tree/feature/pr-pending-1) branch is merged.

### Related Commit
 * [`d516483` Add New Window Definition](https://github.com/Ha-limLee/Sticky-Note-Improved/commit/d516483e84a464cd82fa0003eeb80dfd9831c3cd)

**Comment by Ha-limLee** [comment]
feature/pr-pending-1 branch is merged into develop branch
